version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: resilience_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: resilience_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/internet_resilience
      - JWT_SECRET=internet_resilience_super_secret_jwt_key_2026
      - REFRESH_SECRET=internet_resilience_super_secret_refresh_key_2026
      - CLIENT_ORIGIN=http://localhost:5173
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: resilience_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mongo_data:
