import jsPDF from 'jspdf';
import { api } from '../services/api';

export async function generateMonitoringPDFReport() {
  try {
    const res = await api.get('/export/report');
    const data = res.data;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header Title
    doc.setFillColor(10, 13, 20);
    doc.rect(0, 0, pageWidth, 35, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.text('Internet Resilience Map - Executive Summary Report', 14, 20);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated: ${new Date(data.generatedAt).toLocaleString()} | Account: ${data.user}`, 14, 28);

    // Section 1: Key Metrics
    let y = 48;
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Key Performance Metrics', 14, y);

    y += 10;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const summaryItems = [
      `Total Monitored Endpoints: ${data.summary.totalMonitoredWebsites}`,
      `Online Endpoints: ${data.summary.onlineWebsites}`,
      `Offline Outages: ${data.summary.offlineWebsites}`,
      `Average Uptime: ${data.summary.avgUptimePercentage}%`,
      `Total Incidents Logged: ${data.summary.totalIncidentsRecorded}`,
    ];

    summaryItems.forEach((item) => {
      doc.text(`• ${item}`, 18, y);
      y += 6;
    });

    // Section 2: Website Status List
    y += 8;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Monitored Websites Health Status', 14, y);

    y += 8;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    doc.text('Name', 14, y);
    doc.text('Status', 85, y);
    doc.text('Uptime %', 120, y);
    doc.text('Latency (ms)', 155, y);
    doc.line(14, y + 2, pageWidth - 14, y + 2);

    y += 7;
    doc.setFont('helvetica', 'normal');

    data.websites.forEach((site: any) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.text(String(site.name).substring(0, 30), 14, y);
      doc.text(String(site.status).toUpperCase(), 85, y);
      doc.text(`${site.uptimePercentage}%`, 120, y);
      doc.text(site.lastLatencyMs ? `${site.lastLatencyMs}ms` : '--', 155, y);
      y += 6;
    });

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text('Generated by Internet Resilience Map SaaS Platform - https://resiliencemap.io', 14, 285);

    doc.save(`Resilience_Map_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  } catch (err) {
    console.error('Error generating PDF report', err);
    alert('Failed to generate PDF report.');
  }
}
